### ISSUE TITLE
Неправильная работа метода  self.getAngleTo

### ISSUE THREAD

**Issue by vasily-shakhov** [Megabyteceer/js-cgdk#7]
По документации он возращает значение от [-Math.PI, Math.PI], однако сейчас он может возвращать [-2*Math.PI, 2*Math.PI]

Как исправить:
Заменить код на
getAngleTo = function(x, y) {
      var angle = 0;
      if (typeof x === 'number') {
        angle = Math.atan2(y - this.y, x - this.x) - this.angle;
      } else {
        angle = Math.atan2(x.y - this.y, x.x - this.x) - this.angle;
      }

      if (angle < -Math.PI) {
        angle += 2 * Math.PI
      } else if (angle > Math.PI) {
        angle -= 2 * Math.PI
      }
      return angle
    };

**Comment by Megabyteceer** [comment]
Спасибо, поправил.
